import { Navbar } from "@/components/carepath/navbar";
import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />

      <main className="flex flex-1 flex-col py-12 px-4 md:px-8">
        <div className="mx-auto max-w-4xl space-y-8">
          <div className="space-y-4 border-b pb-8">
            <h1 className="text-4xl font-bold tracking-tight">Terms of Service & Legal Disclaimer</h1>
            <p className="text-muted-foreground text-lg">Last Updated: {new Date().toLocaleDateString()}</p>
            
            <div className="rounded-lg border-2 border-destructive bg-destructive/10 p-6 mt-6">
              <h2 className="text-xl font-bold mb-2 text-destructive">CRITICAL NOTICE: NOT MEDICAL ADVICE</h2>
              <p className="font-semibold text-foreground">
                CarePath is an educational computer science and hackathon project. It is absolutely NOT a medical device, diagnostic tool, or replacement for professional medical advice. By using this service, you acknowledge that you are using experimental software at your own risk.
              </p>
            </div>
          </div>

          <div className="space-y-6 text-foreground/90 leading-relaxed">
            <section className="space-y-3">
              <h2 className="text-2xl font-semibold">1. Acceptance of Terms</h2>
              <p>
                By accessing or using CarePath, you agree to be bound by these Terms of Service. If you do not agree to these terms, you must not use the application.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold">2. No Medical Advice, Diagnosis, or Treatment</h2>
              <p>
                The content provided by CarePath (including but not limited to summaries, action plans, simplified text, and warning signs) is generated by artificial intelligence. <strong>This information is for educational and informational purposes only.</strong>
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>CarePath does <strong>not</strong> practice medicine or provide healthcare services.</li>
                <li>CarePath cannot and does not diagnose medical conditions.</li>
                <li>CarePath cannot and does not recommend or prescribe treatments or medications.</li>
                <li>You must <strong>never</strong> disregard professional medical advice, alter your medications, or delay seeking medical treatment based on information provided by this application.</li>
              </ul>
              <p className="font-semibold mt-2">
                If you think you may have a medical emergency, call your doctor, go to the nearest hospital emergency department, or call emergency services (e.g., 911) immediately.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold">3. Accuracy of Artificial Intelligence</h2>
              <p>
                CarePath relies on Large Language Models (LLMs) to process text. AI can make mistakes, hallucinate information, or misinterpret complex medical jargon.
              </p>
              <p>
                We make no representations or warranties regarding the accuracy, completeness, or usefulness of the generated outputs. It is your sole responsibility to verify any information provided by CarePath against your original medical documents and with your healthcare provider.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold">4. Limitation of Liability</h2>
              <p className="uppercase font-semibold">
                Under no circumstances shall the creator(s), developers, or maintainers of CarePath be liable for any direct, indirect, incidental, consequential, special, or exemplary damages arising from your use of the application.
              </p>
              <p>
                This includes, but is not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Adverse medical outcomes, injury, or death resulting from reliance on the application.</li>
                <li>Loss of data, privacy breaches, or unauthorized access to the information you upload.</li>
                <li>Service interruptions or the complete discontinuation of the application.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold">5. Data Privacy and Security</h2>
              <p>
                CarePath is a portfolio project. While we implement standard security practices, <strong>this application is NOT HIPAA compliant.</strong>
              </p>
              <p>
                By using CarePath, you agree that:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>You upload your personal or medical documents at your own sole risk.</li>
                <li>We do not guarantee the absolute security of your data against unauthorized breaches.</li>
                <li>You are solely responsible for redacting sensitive Personally Identifiable Information (PII) before uploading documents, if you choose to do so.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-2xl font-semibold">6. "As-Is" Service</h2>
              <p>
                CarePath is provided on an "AS IS" and "AS AVAILABLE" basis, without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, and non-infringement.
              </p>
            </section>

            <div className="mt-12 rounded-lg bg-muted p-6 border text-center">
              <p className="text-lg font-medium">
                By continuing to use CarePath, you acknowledge that you have read, understood, and agreed to be legally bound by this disclaimer and these terms.
              </p>
            </div>
          </div>
        </div>
      </main>

      <footer className="border-t py-6 mt-auto">
        <div className="container mx-auto px-4 text-center text-sm text-muted-foreground flex flex-col gap-2">
          <p>This tool does not provide medical advice. Always consult a healthcare professional.</p>
          <p className="space-x-4">
            <Link href="/terms" className="underline hover:text-foreground transition-colors">
              Terms of Service
            </Link>
            <Link href="/privacy" className="underline hover:text-foreground transition-colors">
              Privacy Policy
            </Link>
          </p>
        </div>
      </footer>
    </div>
  );
}
